// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe4hSf2l9d4myC61b3gs1zi9tkNjYMJs8',
    appId: '1:981223545023:web:e892bd0c823218d6678e0a',
    messagingSenderId: '981223545023',
    projectId: 'ayyendance-spit',
    authDomain: 'ayyendance-spit.firebaseapp.com',
    storageBucket: 'ayyendance-spit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQ2xNnACWsdXMRIWFfQ3uYssLWuLfyYM',
    appId: '1:981223545023:android:5bf0ef09e26d73f2678e0a',
    messagingSenderId: '981223545023',
    projectId: 'ayyendance-spit',
    storageBucket: 'ayyendance-spit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVMlgOlqtrc9N-OHDsHO1CG9RbOtJ7Bo',
    appId: '1:981223545023:ios:873fb2501cdd4ab3678e0a',
    messagingSenderId: '981223545023',
    projectId: 'ayyendance-spit',
    storageBucket: 'ayyendance-spit.appspot.com',
    iosClientId: '981223545023-agvdj93ljmc9ga2lm4gjirukh0g8v5kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnVMlgOlqtrc9N-OHDsHO1CG9RbOtJ7Bo',
    appId: '1:981223545023:ios:873fb2501cdd4ab3678e0a',
    messagingSenderId: '981223545023',
    projectId: 'ayyendance-spit',
    storageBucket: 'ayyendance-spit.appspot.com',
    iosClientId: '981223545023-agvdj93ljmc9ga2lm4gjirukh0g8v5kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );
}
